name: test Webpage Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  HTMLHint:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g htmlhint
      - run: htmlhint "**/*.html"
  lychee:
    runs-on: ubuntu-latest
    container:
      image: lycheeverse/lychee:master
    steps:
      - uses: actions/checkout@v4
      - run: lychee .
  eslint:
    runs-on: ubuntu-latest
    container:
      image: cytopia/eslint
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apk update
          sudo apk add nodejs npm
          apk update && apk add nodejs npm
          npm init -y
          npm install --save-dev eslint eslint-plugin-html
          npm install --save-dev eslint-plugin-html
          npx eslint --ext .html,.js src


